version: "3.4"

services:
  nginx:
    image: nginx:1.23.4-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/data:/etc/nginx/data
