version: "3.4"

services:
  nginx:
    image: nginx:1.26.2-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/njs:/etc/nginx/njs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_BODY=world
