version: "3.4"

services:
    nginx:
        image: nginx:1.23.4-alpine
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/njs:/etc/nginx/njs
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    upstream:
        image: node:14.16.0-buster
        container_name: upstream
        ports:
            - 5015:5015
        volumes:
            - ./upstream:/home/node/app
        working_dir: /home/node/app
        command: "npm start"
