version: "3.4"

services:
  nginx:
    build: nginx
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/njs:/etc/nginx/njs
      - ./nginx/conf.d:/etc/nginx/conf.d
    command: "/usr/local/start-nginx.sh"
