version: "3.4"

services:
  nginx:
    build: nginx
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/njs:/etc/nginx/njs
      - ./nginx/conf.d:/etc/nginx/conf.d

  node:
    image: node:18-alpine
    container_name: node
    user: "node"
    working_dir: /home/node/app
    ports:
      - 5015:5015
    volumes:
      - ./support/node:/home/node/app
    command: "npm start"
