version: "3.4"

services:
    nginx:
        image: nginx:1.23.4-alpine
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d

    api:
        image: node:18-alpine
        container_name: api
        user: "node"
        working_dir: /home/node/app
        ports:
            - 5015:5015
        environment:
            - PORT=5015
        volumes:
            - ./api:/home/node/app
            - ../support/yop:/home/node/app/yop
        command: "npm start"
