version: "3.4"

services:
    nginx:
        image: nginx:1.23.4-alpine
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/public:/usr/share/nginx/html

    api:
        image: node:14.16.0-buster
        container_name: api
        ports:
            - 5015:5015
        volumes:
            - ./api:/home/node/app
        working_dir: /home/node/app
        command: "npm start"
