name: njs-hello

on:
    push:
        branches:
            - master

jobs:
    test:
        name: run tests
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: start nginx
              run: |
                  cd njs-hello
                  docker-compose up -d
            - name: run tests
              run: |
                  ./support/test.sh ./njs/hello.sh
