name: payload_filter

on:
  push:
    branches:
      - master

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          cd payload_filter
          docker-compose build
      - name: create matching file
        run: |
          cd payload_filter
          touch ./nginx/conf.d/matching
      - name: test config
        run: |
          cd payload_filter
          docker-compose run --rm nginx nginx -t
      - name: start servers
        run: |
          cd payload_filter
          docker-compose up -d
          sleep 5
      - name: inspect
        run: |
          cd payload_filter
          env
          docker ps -a
          ./inspect.sh
          ls -l /etc/hosts
          cat /etc/hosts
      - name: run tests
        run: |
          cd payload_filter
          ../testing/test.sh ./about
