name: payload_filter

on:
    push:
        branches:
            - master

jobs:
    test:
        name: run tests
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: run tests
              run: |
                  cd payload_filter/about
                  ../../testing/test.sh .
