name: payload_filter

on:
    push:
        branches:
            - master

jobs:
    test:
        name: run tests
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: start nginx
              run: |
                  cd payload_filter/about
                  docker-compose up -d
            - name: run tests
              run: |
                  ./testing/test.sh ./payload_filter/about/tests.sh
