name: proxy_get_body

on:
  push:
    branches:
      - master

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          cd proxy_get_body/about
          docker-compose build
      - name: start servers
        run: |
          cd proxy_get_body/about
          docker-compose up -d
      - name: run tests
        run: |
          cd proxy_get_body
          ../testing/test.sh ./about
