name: proxy_set_header

on:
  push:
    branches: 
      - master

jobs:

  test:
    name: run tests
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: start nginx
        run: |
          cd proxy_set_header
          docker-compose up -d
      - name: run tests
        run: |
          ./testing/test.sh ./proxy_set_header/tests.sh
