name: proxy_or_stub

on:
    push:
        branches:
            - master

jobs:
    test:
        name: run tests
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: start nginx
              run: |
                  cd proxy_or_stub
                  docker-compose up -d
            - name: run tests
              run: |
                  cd proxy_or_stub
                  ../support/test.sh ./about
