name: proxy-get-body

on:
    push:
        branches:
            - master

jobs:
    test:
        name: run tests
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2
            - name: update /etc/hosts
              run: |
                  sudo echo "172.17.0.1 host.docker.internal" | sudo tee -a /etc/hosts
                  cat /etc/hosts
            - name: build
              run: |
                  cd proxy-get-body
                  docker-compose build
            - name: start servers
              run: |
                  cd proxy-get-body
                  docker-compose up -d
            - name: run tests
              run: |
                  cd proxy-get-body
                  ../support/test.sh ./about
